### PR TITLE
Made the startup script work on macos

### PR DESCRIPTION
**Pull request by rlyshw**
Solves issue #10 . 

Some of the syntax in the startup script was not compatible with macos. This fixes that!

### CODE REVIEW

**Comment by OrdinatorStouff** [comment]
Have you confirmed that this same sh still works with Linux bash all the same? It looks like it should just fine considering it's just some if/else logic but I'd like to know for sure before we merge

**Comment by rlyshw** [comment]
I have not tried, maybe after finals I can give it a go, or someone else could pull it down and confirm.

**Comment by mrsmn** [comment]
Works fine on both Darwin and Linux 👍 Can be merged IMHO.

**Comment by mrsmn** [comment]
@OrdinatorStouff any plans of this being merged anytime soon? This issue is quite blocking on Darwin. Cheers.

**Comment by OrdinatorStouff** [comment]
Yes, I haven't forgot about this I was just also hoping to figure out the windows bat file delimiter issue and update everything at the same time.

probably no reason though since I don't think that issue affects the sh, just windows

**Pull request merged**
